services:
  ada-ui:
    image: rodekruis/ada-ui
    build: .
    restart: on-failure:5
    env_file: .env
    volumes:
      - client-root:/home/node/app/www
    networks:
      - client

  nginx:
    image: staticfloat/nginx-certbot
    restart: on-failure:5
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/https.conf:/etc/nginx/user.conf.d/ada.conf
      - letsencrypt:/etc/letsencrypt
      - client-root:/www/data
    depends_on:
      - ada-ui
    networks:
      - client

volumes:
  letsencrypt:
  client-root:

networks:
  client:
